development:
  adapter: postgresql
  encoding: unicode
  database: bookbox_development
  pool: 5
  username: bookbox
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bookbox_test
  pool: 5
  username: bookbox
  password:
