development:
  adapter: postgresql
  encoding: unicode
  database: bookbox_development
  host: localhost
  pool: 5
  username: bookbox
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bookbox_test
  host: localhost
  pool: 5
  username: bookbox
  password:
