# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1bdb9f68956ba027aa27881ea956c928d22778903287ade9a6d35faf93046a3844797826e919a4dcf74ff43029b47d535fa7630a82ad62b63fbb56e1d88e885

test:
  secret_key_base: cf5a730a794e45e63e4ac48036a6ad1300ea72e7e4230cf5af74cc90071794e9fa36c88118da8561a3a786992e0402a6539af172fadaf6dedc04b9ab2a0d8e4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
